# Generated by Django 4.0.2 on 2022-02-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('alias', models.CharField(max_length=64)),
                ('sort_order', models.IntegerField(verbose_name='порядок сортировки')),
            ],
        ),
    ]
