# Generated by Django 4.0.2 on 2022-03-05 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(limit_value=10, message='The value must be between 1 and 10.')], verbose_name='Rating'),
        ),
    ]
