# Generated by Django 4.0.2 on 2022-02-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hub_id',
            new_name='hub',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
