# Generated by Django 4.0.2 on 2022-03-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('posts', '0010_post_tags_alter_post_slug_alter_post_status'),
    ]

    operations = [
    ]
