# Generated by Django 4.0.2 on 2022-02-27 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notification_target_user_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_target', to=settings.AUTH_USER_MODEL, verbose_name='Адресат'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
