# Generated by Django 4.0.2 on 2022-03-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_alter_notification_target_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_target', to=settings.AUTH_USER_MODEL, verbose_name='Адресат'),
        ),
    ]
